INSERT INTO Sensor (name, type, unit, location) VALUES ("Temperature Bedroom", "Temperature", "Celcius", "Bedroom"),
    ("Temperature Kitchen", "Temperature", "Celcius", "Kitchen"),
    ("Temperature Bathroom", "Temperature", "Celcius", "Bathroom"),
    ("Humidity Bedroom", "Humidity", "÷", "Bedroom"),
    ("Humidity Kitchen", "Humidity", "÷", "Kitchen"),
    ("Humidity Bathroom", "Humidity", "÷", "Bathroom"),
    ("Light Bedroom", "Light", "Lux", "Bedroom"),
    ("Light Kitchen", "Light", "Lux", "Kitchen"),
    ("Light Bathroom", "Light", "Lux", "Bathroom"),
    ("PM2.5 Bedroom", "PM2.5", "µg/m³", "Bedroom"),
    ("PM2.5 Kitchen", "PM2.5", "µg/m³", "Kitchen"),
    ("PM2.5 Bathroom", "PM2.5", "µg/m³", "Bathroom"),
    ("PM10 Bedroom", "PM10", "µg/m³", "Bedroom"),
    ("PM10 Kitchen", "PM10", "µg/m³", "Kitchen"),
    ("PM10 Bathroom", "PM10", "µg/m³", "Bathroom"),
    ("CO2 Bedroom", "CO2", "ppm", "Bedroom"),
    ("CO2 Kitchen", "CO2", "ppm", "Kitchen"),
    ("CO2 Bathroom", "CO2", "ppm", "Bathroom");

INSERT INTO Data (value, unit, sensor_id) VALUES
    (2 ,"Celcius", 1),
    (15 ,"Celcius", 2),
    (17 ,"Celcius", 3),
    (30 ,"÷", 4),
    (80 ,"÷", 5),
    (55 ,"÷", 6),
    (10 ,"Lux", 7),
    (150 ,"Lux", 8),
    (60 ,"Lux", 9),
    (30 ,"µg/m³", 10),
    (80 ,"µg/m³", 11),
    (55 ,"µg/m³", 12),
    (45 ,"µg/m³", 13),
    (52 ,"µg/m³", 14),
    (101 ,"µg/m³", 15),
    (1100 ,"ppm", 16),
    (900 ,"ppm", 17),
    (2100 ,"Lux", 18);